"""Regenerate every analysis table, figure and paper macro from the recorded runs, in one command.

  cd v2 && python -m analysis.make_all                       # every run in v2/runs except selftest* / smoke*
  cd v2 && python -m analysis.make_all --runs main,sweep,heldout --out reports/results/analysis

Sections (see reports/ANALYSIS_PLAN.md): a01 overview, statuses, cost, tiers, variance; a02 attribution (H1-H7);
a03 scale and held-out; a04 repair (H8) and oracle channel bounds; a05 validity on live outputs, kernel build,
failure taxonomy, sufficiency list; figures. Every number the paper quotes is also written as a LaTeX macro in
<out>/paper_numbers.tex, so the text cannot drift from the data.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
import time
from pathlib import Path

V2 = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(V2))
from analysis import a01_overview, a02_attribution, a03_generalization, a04_repair, a05_validity, figures  # noqa: E402
from analysis.common import load, run_dirs  # noqa: E402


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="", help="comma-separated run directory names (default: all real runs)")
    ap.add_argument("--out", default=str(V2 / "reports" / "results" / "analysis"))
    ap.add_argument("--skip", default="", help="comma-separated sections to skip, e.g. a05")
    a = ap.parse_args(argv)
    names = [x for x in a.runs.split(",") if x] or None
    dirs = run_dirs(names)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    s, r = load(names)
    if s.empty:
        sys.exit(f"no scores found in {[d.name for d in dirs]}")
    print(f"{len(s)} score records from {[d.name for d in dirs]}")
    skip = set(a.skip.split(","))
    macros = {}
    for name, fn in (("a01", lambda: a01_overview.run(s, r, out)), ("a02", lambda: a02_attribution.run(s, r, out)),
                     ("a03", lambda: a03_generalization.run(s, r, out, dirs)),
                     ("a04", lambda: a04_repair.run(s, r, out, dirs)), ("a05", lambda: a05_validity.run(s, r, out, dirs))):
        if name in skip:
            continue
        t0 = time.time()
        macros.update(fn() or {})
        print(f"  {name} done in {time.time() - t0:.0f}s")
    figures.run(s, out)
    stamp = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    lines = [f"% generated by v2/analysis/make_all.py at {stamp} from runs: {', '.join(d.name for d in dirs)}"]
    lines += [f"\\newcommand{{{k}}}{{{v}}}" for k, v in sorted(macros.items())]
    (out / "paper_numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {len(macros)} macros and the section reports to {out}")


if __name__ == "__main__":
    main()
